### ISSUE TITLE
I'd like to have credential to access API

### ISSUE THREAD

**Issue by arecavn** [careerbuilder/DataScienceAPIDocumentation#16]
Hi,
Your APIs provide great features. I'd like to have credential to access APIs.
Please help.
Thanks in advance.

**Comment by thomasmahoney** [comment]
Hey @arecavn, thanks for your interest in our APIs. Could you tell us a little more about your use case? What company/organization, if any, are you working with? Looking forward to hearing back from you.

**Comment by arecavn** [comment]
Hi @thomasmahoney,
Thanks for reply. I just want to see first, if it's good and I'd like to use for my system, I will provide more info. Is it fine?
